### ISSUE TITLE
parse SoftConf submissions into metadata

### ISSUE THREAD

**Issue by ejhumphrey** [ismir/conference-archive#11]
starting from the submission info from softconf + PDF publications, produce two files:
- markdown in the format expected by DBLP, [like this](https://github.com/stefan-balke/DBLP-conference/blob/master/templates/template_dblp.txt)
- JSON for the Zenodo uploader script, [like this](https://github.com/ismir/conference-archive/blob/master/scripts/archive_collection.py#L17)

**Comment by stefan-balke** [comment]
Can you provide an example CSV output?
Then I can port my scripts and integrate them here.
