### ISSUE TITLE
do authors prefer YAML to JSON?

### ISSUE THREAD

**Issue by ejhumphrey** [ismir/conference-archive#16]
in the future, it may be preferable to store all metadata as YAML, so that humans may more easily correct errors. This is important because it the metadata maintained here is meant to act at the single source of truth, and that Zenodo (and others) should inherit from it. 

the question then is, is it actually painful for users to manually update JSON? would YAML make this easier? are comments (`# i'm a comment`) useful?

**Comment by stefan-balke** [comment]
JSON it is.
