### ISSUE TITLE
Download 2018

### ISSUE THREAD

**Issue by stefan-balke** [ismir/conference-archive#29]
Hey,

I was not able to download the PDFs for 2018. Always results in ~100 byte-ish files.

`python download_proceedings.py ../database/proceedings/2018.json ../database/pdfs`

Can you reproduce this?

**Comment by ejhumphrey** [comment]
hum that's odd ... but I wonder, do we still need to? the PDFs have been successfully cloned from the URL that the organizers had tweeted out, and they also made it back in the conference website upload http://github.com/ismir/ismir2018

**Comment by stefan-balke** [comment]
No, I think this is obsolete with the new file structure.
