### ISSUE TITLE
Publication identifier namespace and index

### ISSUE THREAD

**Issue by ejhumphrey** [ismir/conference-archive#9]
I had been hoping we could use DBLP's naming convention for "primary keys" over papers, but it looks like the convention may be difficult to follow independently. There are at least two side-effects that would be difficult to model:
- keys that would create collisions are suffixed with alpha-enumeraters, e.g. a,b,c...
- author names are derived from DBLPs global author namespace, and an ISMIR author may have a different representation as a result.

An obvious place this should happen at the point of submission in a given conference, e.g. `event_id-submission_id` where event ID is year (for now). 

Perhaps there would be value to producing (and maintaining) a table / CSV index of paper identifiers in different namespaces? Some of these are (effectively) non-deterministic, so there doesn't really seem to be a good way around it. The three columns that seem important so far would be:
- ISMIR: `{event_id}-{submission_id}`, e.g. 2017-103
- Zenodo: integer "record ID", e.g. 1417159
- DBLP: mix of authors + year, e.g. FonsecaPFFBFOPS17

**Comment by stefan-balke** [comment]
+1 for DBLP since it's semantically easy to understand.

**Comment by ejhumphrey** [comment]
update: we're keeping them all! see #31
